### PR TITLE
Use gen_fsm_compat for r20 compatibility

### PR DESCRIPTION
**Pull request by Licenser**
yay r20 plz?

### CODE REVIEW

**Comment by Licenser** [comment]
@tsloughter pinging the ensemble master!

**Review by tsloughter — APPROVED** [review]

**Comment by tsloughter** [comment]
Looks good. But whats going on with official basho repos these days? Guess I can take this discussion to portriak slack...

**Comment by Licenser** [comment]
They're still going but at a slower pace (which is fine, stability concerns are different) so this is kind of a nice staging ground for r20/21 work.

**Comment by Licenser** [comment]
@tsloughter can you publish develop to hex? it's already bumped but I don't have the permissioins

**Comment by tsloughter** [comment]
Done.

**Comment by Licenser** [comment]
thx!

**Pull request merged**
